<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Promise</title>
    <style>
        img{
            width: 400px;
        }
    </style>
</head>
<body>
    <script>
        let a,b;
        function program(cb){
            setTimeout(function(){
                a = 3;
                b = 4;
                cb();
            },0);
        }
        function sum(){
            let c = a + b;
            console.log(c); // NaN
        }
        program(sum);
        
        console.log(Promise);

        // function timeout(ms){
        //     return new Promise(function(resolve,reject){
        //         setTimeout(resolve,ms,'done');
        //     });
        // }
        // timeout(100).then(function(value){
        //     console.log(value);
        // });
        
        // function time(ms){
        //     return new Promise(function(resolve,reject){
        //         setTimeout(resolve('done'),ms);
        //     });
        // }
        // time(100).then(function(value){
        //     console.log(value);
        // })

        let promise = new Promise(function(resolve,reject){
            console.log('Promise');
            resolve();
        });
        promise.then(function(){
            console.log('resolved');
        });
        console.log('Hi');
        // Promise Hi resolved


        let p = new Promise(function(resolve,reject){
            console.log('Primise');
            resolve('resolved');
        });
        p.then(function(data){
            console.log(data);
        });
        console.log('Hi');


        var state = 1;
        function step1(){
            if(state == 1){
                console.log('1. 洗菜做饭');
            }else{
                console.log('1.洗菜做饭-失败');
            }
        }
        function step2(){
            if(state == 1){
                console.log('2. 吃饭');
            }else{
                console.log('2.吃饭-失败')
            }
        }
        function step3(){
            if(state == 1){
                console.log('3. 收拾碗筷');
            }else{
                console.log('3. 收拾碗筷失败');
            }
        }

        new Promise(step1).
        then(function(val){
            console.log(val);
            return new Promise(step2);
        })
        .then(function(val){
            console.log(val);
            return new Promise(step3);
        })
        .then(function(val){
            console.log(val);
        });


        let Timer = setTimeout(function(data){
            console.log(data);
        },1000,'Hello World');

        function loadImg(url){
            return new Promise(function(resolve,reject){
                const image = new Image();
                image.onload = function(){
                    resolve(image);
                }
                image.onerroe = function(){
                    reject(new Erroe('could not load image at' + url));
                }
                image.src = url;
                document.body.appendChild(image);
            })
        };
        
        loadImg('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1551929681&di=236008f04b7b55d8dc7ea2f4d3a32e82&imgtype=jpg&er=1&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201705%2F24%2F20170524002612_UuSTK.jpeg');
        
        const p1 = new Promise(function(resolve,reject){
            throw new Error('test');
        });
        p1.catch(function(error){
            console.log(error);
        })

        const p2 = new Promise(function(resolve,reject){
            try{
                throw new Error('test');
            }catch(e){
                reject(e);
            }
        });
        p2.catch(function(error){
            console.log(error);
        });

        const p3 = new Promise(function(resolve,reject){
            reject( new Error('test') );
        });
        p3.catch(function(error){
            console.log(error);
        });

        // 如果Promise状态已经变成resolved，再抛出错误时无效的。
        const promise1 = new Promise(function(resolve,reject){
            resolve('ok');
            throw new Error('test');
        });
        promise1.then(function(value){
            console.log(value);
        }).catch(function(error){
            console.log(error);
        });

        const someAsyncThing = function(){
            return new Promise(function(resolve,reject){
                resolve(x + 2);
            });
        };
        someAsyncThing().then(function(){
            console.log('everything is great');
        });
        setTimeout(function(){
            console.log(123);
        },2000);

        function fun(){
            return new Promise(function(resolve,reject){
                resolve(x + 1);
            })
        }
        fun().then(function(){
            console.log('Hello World');
        }).catch(function(){
            console.log('error');
        });

        const promise2 = new Promise(function(resolve,reject){
            resolve('it is ok');
            setTimeout(function(){
                throw new Error('test')
            },0);
        });
        promise2.then(function(value){
            console.log(value);
        });


        const f1 = function(){
            return new Promise(function(resolve,reject){
                resolve(x + 2);
            });
        }
        f1().catch(function(error){
            console.log('oh no',error);
        }).then(function(){
            console.log('carry on');
        });

        Promise.resolve()
        .catch(function(error){
            console.log('oh no error');
        })
        .then(function(){
            console.log('carry on');
        });

        function m1(){
            return new Promise(function(resolve,reject){
                resolve(x + 2);
            });
        };
        m1().then(function(){
            return m1();
        }).catch(function(error){
            console.log('oh no,error');
            y + 2;
        }).then(function(){
            console.log('carry on');
        });

        m1().then(function(){
            return m1();
        }).catch(function(error){
            y + 2;
            console.log('oh on',error);
        }).catch(function(error){
            console.log('carry on',error);
        });

    </script>
</body>
</html>